
GET http://localhost:3000/ads/

###
GET http://localhost:3000/ads/ville/Bordeaux

###
DELETE http://localhost:3000/ads/price/40

###
PUT http://localhost:3000/ads/Septembre/1er
Content-Type: application/json
{
    
}

###
GET http://localhost:3000/categorie/vêtement

###
GET http://localhost:3000/categorie/v&v

###
GET http://localhost:3000/categorie/average/autre

###
GET http://localhost:3000/categorie/startingWith/v